name: image
on:
  push:
    paths:
      - '.github/**'
  workflow_dispatch:

jobs:
  image:

    runs-on: ubuntu-20.04
    container: fpgaarcade/replay-rootfs:latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: build
      run: ./build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: replay_de10_image
        path: image

    - uses: actions/upload-artifact@v2
      with:
        name: replay_de10_update
        path: update
