name: image
on:
  push:
    tags: 
      - '*'
    paths:
      - '.github/**'
  
  workflow_dispatch:

jobs:
  image:

    runs-on: ubuntu-20.04
    container: fpgaarcade/replay-rootfs:latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: build
      run: HOME=/root ./build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: replay_de10_image
        path: image

    - uses: actions/upload-artifact@v2
      with:
        name: replay_de10_update
        path: update

    - uses: actions/upload-artifact@v2
      with:
        name: build_stats
        path: stats

    - uses: montudor/action-zip@v1
    
    - if: startsWith(github.ref, 'refs/tags/')
      run: zip -qq -r $GITHUB_WORKSPACE/replay_de10_image_${{ env.TAG }}.zip *
      working-directory: image

    - if: startsWith(github.ref, 'refs/tags/')
      run: zip -qq -r $GITHUB_WORKSPACE/replay_de10_update_${{ env.TAG }}.zip *
      working-directory: update

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
        files: |
          *.zip
